### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by computman007** [linuxnico/pluginSNMP#1]
Hello

Any document available how to configure this Jeedom Plugin ?

**Comment by linuxnico** [comment]
hi, 
sorry, 
you just have to inform, the IP of the equipment and the OID of the value you want.

the OID depends of your equipment.

sorry for my english, i'm french

ps: attention to install dependances, in the config menu of the plugin

**Comment by computman007** [comment]
Je suis aussi français.

L'interface ne permet pas de renseigner ces informations ni d'ailleur de saisir les information de communauté si ce n'est pas "public"

![2021-02-03 14_34_27-Window](https://user-images.githubusercontent.com/25824896/106754247-08ac4080-662d-11eb-919c-d67a2af5a5f6.png)


Les dépendances semblent OK et installées automatiquement
![2021-02-03 14_36_09-](https://user-images.githubusercontent.com/25824896/106754446-4a3ceb80-662d-11eb-9de9-21d03b180550.png)

**Comment by linuxnico** [comment]
le plugin a été développé pour  la communauté public seuleument. ( c'est une bonne idée d'amélioration!!)

pour config:
sur la page principale du plugin, il faut juste renseigner l'adresse ip, ensuite dans les commandes, créer une nouvelle commande et ensuite le type de donnee (numérique,...) et l'oid voulu 

je vais regarder pour améliorer et integrer  la possibilité de communauté autre que public et avec les identifiants.

**Comment by computman007** [comment]
ça fonctionne du coup :)

Peut-etre juste mettre ces quelques indications dans la documentation (le lien cliqué dans l'interface de Jeedom)
