### ISSUE TITLE
Le pooling ne respect pas le réglage cron

### ISSUE THREAD

**Issue by computman007** [linuxnico/pluginSNMP#2]
Bonjour,

Les données ne semble remonter de façon à respecter le réglage de cron

Y-a-t-il un paramètre à régler qqpart ?

![2021-02-04 11_17_23-Snmp_client - Jeedom - Vivaldi](https://user-images.githubusercontent.com/25824896/106879068-fbe62600-66da-11eb-854d-0e1d80bb1d67.png)
![2021-02-04 11_17_02-](https://user-images.githubusercontent.com/25824896/106879073-fc7ebc80-66da-11eb-8959-376ed52750dc.png)

**Comment by linuxnico** [comment]
Bizarre, je viens de passer le mien a 1min pour test et chez moi ca fonctionne. 

1) est ce que tu a rempli la ligne du cron a la main ou avec le point d'interrogation?
2) est ce que l'historique du ping montre la meme chose?
3) est ce que tu peut regarder dans les logs "temps reel" pour voir si la commande passe bien toute les minutes et ça serai l'affichage qui déconne?

**Comment by computman007** [comment]
> Bizarre, je viens de passer le mien a 1min pour test et chez moi ca fonctionne.
> 
> 1. est ce que tu a rempli la ligne du cron a la main ou avec le point d'interrogation?
> 2. est ce que l'historique du ping montre la meme chose?
> 3. est ce que tu peut regarder dans les logs "temps reel" pour voir si la commande passe bien toute les minutes et ça serai l'affichage qui déconne?

1. Avec le point d'interrogation
2. le ping n'est pas régulier non plus
![2021-02-04 14_08_50-Historique - Jeedom - Vivaldi](https://user-images.githubusercontent.com/25824896/106902624-542c2080-66f9-11eb-9d2e-0f0f6b3da3e9.png)

3. Je viens de tout refaire et pour le moment ça semble fonctionner... je garde le point ouvert et si résolu je clos

**Comment by linuxnico** [comment]
est ce que ton jeedom est tres charge?

**Comment by computman007** [comment]
> est ce que ton jeedom est tres charge?

Charge | 0.98 - 1.01 - 0.88

**Comment by linuxnico** [comment]
oui donc pas de surcharge... 
tiens moi au courant

**Comment by computman007** [comment]
après avoir resaisie les paramètres ça fonctionne. pas d'explications
