### ISSUE TITLE
Le plug in ne pool plus les infos sans raison

### ISSUE THREAD

**Issue by computman007** [linuxnico/pluginSNMP#3]
Bonjour

J'ai toujours un retour de valeur à 0 et je ne comprends pas pourquoi

Les logs ne donnent rien même en débug

Quand je test avec un snmpwalk ça retourne bien la valeur depuis une autre machine donc ce n'est pas le Synology qui déconne

[2021-05-11 01:42:44][DEBUG] : on refresh une commande numero: 1050 de type: numeric avec oid: 1.3.6.1.4.1.6574.1.2-2
[2021-05-11 01:42:44][DEBUG] : recupnumerique: oid: -1.3.6.1.4.1.6574.1.2- et ip: -172.16.0.54- et resultat: --
[2021-05-11 01:42:44][DEBUG] : valeur: -- mesuree: --
[2021-05-11 01:42:44][DEBUG] : on refresh une commande numero: 1051 de type: binary avec oid: -2
[2021-05-11 01:42:44][DEBUG] : recupbinaire: oid: -- et ip: -172.16.0.54- et resultat: --
[2021-05-11 01:42:44][DEBUG] : valeur: -- mesuree: --
[2021-05-11 01:42:44][DEBUG] : ping

**Comment by linuxnico** [comment]
bonjour,

est ce que c'est une nouvelle command eou une commande existante qui ne marche plus?
avez vous essayer avec snmpget plutot que walk? (snmpget recuper QUE l'oid passer en parametre contrairement a snmpwalk, qui va recuperer les oids inferieurs)

**Comment by linuxnico** [comment]
la commande 1051 ne contient pas d'oid, mais j epense que c'etait un test
1.3.6.1.4.1.6574.1.2 correspond a la temperature, c'est ca?

**Comment by linuxnico** [comment]
je pense a un truc aussi, la communaute doit etre "public" en minuscule et pas  de majuscule
peut etre a mettre en auto dans une version future

**Comment by computman007** [comment]
Désolé du temps pour répondre #vacances

La communauté est bien en public
C'est une commande qui fonctionnait très bien et s'est arreté de fonctionner (j'ai retiré et remis le plug-in sans succès)
C'est bien la température que je cherche à récupérer avec la commande 1050 (la 1051 c'est pour la présence réseau/ping)

Un snmpget retourne bien la valeur de la température (j'ai rajouté le 0 à la fin depuis le premier test)
![2021-05-19 00_44_23-pi@raspberrypi_ ~](https://user-images.githubusercontent.com/25824896/118732844-66127900-b83b-11eb-8e17-004084cfb371.png)

**Comment by computman007** [comment]
Il fallait cliquer sur le bouton 2 pour appliquer les changements et non sur le bouton 1 comme sur tous les plug in

ça fonctionne du coup

![2021-05-19 00_52_13-Clipboard](https://user-images.githubusercontent.com/25824896/118733433-87279980-b83c-11eb-9245-9a11fd816295.png)
